version: '3'

services:
  db_postgresql:
    image: postgres:10.6-alpine
    env_file:
      - ./docker/db_postgresql/conf/db_conf_env
    volumes:
      - ./databases/postgresql_main_apps:/var/lib/postgresql/data
    container_name: db_postgres_main
    networks:
      - fitness_club_to_postgresql
  
  fitness_club:
    build: ./docker/fitness_club/
    environment:
      PRODUCTION: 'true'
    volumes:
      - ./fitness_club/src:/fitness_club/src
      - ./fitness_club/static:/fitness_club/static
      - ./fitness_club/media:/fitness_club/media
    container_name: Fitness_Club_Frontend_uwsgi_django
    env_file:
      - ./docker/db_postgresql/conf/db_conf_env
    depends_on:
      - db_postgresql
      - solr
    networks:
      - nginx_to_fitness_club
      - fitness_club_to_postgresql
      - fitness_club_to_solr

  server:
    build: ./docker/server/
    volumes:
      - ./fitness_club/static:/fitness_club/static
      - ./fitness_club/media:/fitness_club/media
    ports:
      - 80:80
    container_name: server_nginx
    networks:
      - nginx_to_fitness_club
    depends_on:
      - fitness_club

  solr:
    build: ./docker/solr
    container_name: solr
    volumes:
      - ./databases/solr:/opt/solr/data
    networks:
      - fitness_club_to_solr

networks:
  nginx_to_fitness_club:
    driver: bridge
  fitness_club_to_postgresql:
    driver: bridge
  fitness_club_to_solr:
    driver: bridge